services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: contratos_php
    volumes:
      - .:/var/www/html
    networks:
      - contratos_network
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://contratos_user:contratos_password@database:5432/contratos_db?serverVersion=16&charset=utf8
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: '${JWT_PASSPHRASE:-contratos_jwt_secret}'
      APP_ENV: '${APP_ENV:-dev}'
      APP_SECRET: '${APP_SECRET:-contratos_app_secret_key_change_in_production}'

  nginx:
    image: nginx:alpine
    container_name: contratos_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - contratos_network
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    container_name: contratos_postgres
    environment:
      POSTGRES_DB: contratos_db
      POSTGRES_USER: contratos_user
      POSTGRES_PASSWORD: contratos_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contratos_network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "contratos_db", "-U", "contratos_user"]
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  contratos_network:
    driver: bridge

volumes:
  postgres_data:
